name: Docker Image CI

on: 
  - push
  - workflow_dispatch 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: "registry.codecoffee.org"
          username: "admin"
          password: "admin"

      - name: Get commit SHA
        id: vars
        run: echo "::set-output name=commit_sha::$(echo ${GITHUB_SHA} | cut -c1-7)"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            registry.codecoffee.org/401-ok:${{ steps.vars.outputs.commit_sha }}
            registry.codecoffee.org/401-ok:latest
